
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ltr
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]
  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ltr
      STRIPE_SECRET: <set in env>
      STRIPE_WEBHOOK_SECRET: <set in env>
      DAILY_CAP_USD: 2000
      MONTHLY_CAP_USD: 10000
      OFAC_BLOCKLIST: "CU,IR,KP,SY,UA-43,UA-14,RU"
      POST_CHECKOUT_SUCCESS_URL: http://localhost:8080/success
      POST_CHECKOUT_CANCEL_URL: http://localhost:8080/cancel
    ports: ["8080:8080"]
    depends_on: ["db"]
  mint:
    build: ./mint
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ltr
      AMOY_RPC_URL: https://rpc-amoy.polygon.technology/
      MINTING_PRIVATE_KEY: <set in env>
      MC_TOKEN_ADDRESS: <set in env>
    depends_on: ["db"]
volumes:
  pg:
