app = "love-transcends-api"
primary_region = "lax"
[build]
  dockerfile = "./server/Dockerfile"
[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
