services:
  - type: web
    name: ltr-server
    runtime: node
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ltr-db
          property: connectionString
    buildCommand: "npm ci"
    startCommand: "npm start"
    rootDir: server
  - type: worker
    name: ltr-mint
    runtime: node
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ltr-db
          property: connectionString
    buildCommand: "npm ci"
    startCommand: "npm start"
    rootDir: mint
databases:
  - name: ltr-db
